name: DrakesCore
version: 1.0
main: me.jackstar.drakescraft.DrakesCore
api-version: '1.20'
authors: [JackStar]
description: Core plugin for DrakesCraft
softdepend: [PlaceholderAPI, Vault]
commands:
  drakescrates:
    description: Admin command for DrakesCrates
    usage: /drakescrates <givekey|editor|reload>
    permission: drakescrates.admin
  drakestech:
    description: Admin command for DrakesTech
    usage: /drakestech give <player> <machine_id>
    permission: drakestech.admin
  rank:
    description: Rank administration command
    usage: /rank <set|create|permission>
    permission: drakesranks.admin
permissions:
  drakescrates.admin:
    description: Allows use of DrakesCrates admin command
    default: op
  drakestech.admin:
    description: Allows use of DrakesTech admin command
    default: op
  drakesranks.admin:
    description: Allows use of DrakesRanks admin command
    default: op

